[tool]
[tool.poetry]
name = "noxusbot_deploy"
version = "1.0"
description = "Automatic Deploy noxusbot to Heroku"
authors = ["Noxus"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
